[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/prototype"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
FLASK_ENV = "production"
PORT = "8000"
DATABASE_URL = "sqlite:///passive_captcha.db"
REDIS_URL = "redis://localhost:6379"
SECRET_KEY = "demo-prototype-secret-key-change-in-production"

[[services]]
name = "passive-captcha-prototype"
port = 8000

[prototype]
enabled = true
endpoints = [
  "/prototype",
  "/prototype/api/analytics",
  "/prototype/api/verify", 
  "/prototype/integration-demo",
  "/prototype/live"
]

[features]
realtime_analytics = true
websocket_support = true
demo_integration = true
api_testing = true
live_monitoring = true