[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python app.py --env production --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
FLASK_ENV = "production"
LOG_LEVEL = "INFO"
SERVE_FRONTEND = "true"
ENABLE_WEBSOCKET = "true"
ENABLE_RATE_LIMITING = "true"
RATE_LIMIT_REQUESTS = "1000"