[[services]]
name = "passive-captcha-backend"

[services.source]
repo = "Riishi-01/Passive-Captcha-Model"
branch = "main"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile.production"

[services.deploy]
startCommand = "python main.py --host 0.0.0.0 --port $PORT --gunicorn"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment Variables
[services.variables]
ENV = "production"
FLASK_ENV = "production"
PYTHONPATH = "/app/backend"
API_BASE_URL = "https://${{RAILWAY_PUBLIC_DOMAIN}}"
ALLOWED_ORIGINS = "https://${{RAILWAY_PUBLIC_DOMAIN}},https://*.railway.app,https://passive-captcha-model-production.up.railway.app"

# Database
DATABASE_URL = "${{DATABASE_URL}}"

# Redis (optional - will fall back to in-memory if not available)
REDIS_URL = "${{REDIS_URL}}"

# Authentication
JWT_SECRET = "${{JWT_SECRET}}"
ADMIN_SECRET = "${{ADMIN_SECRET}}"

# ML Model paths
MODEL_PATH = "models/passive_captcha_rf.pkl"
SCALER_PATH = "models/passive_captcha_rf_scaler.pkl"

# Logging
LOG_LEVEL = "INFO"
STRUCTURED_LOGGING = "true"

# Rate limiting
RATE_LIMIT_ENABLED = "true"
RATE_LIMIT_PER_MINUTE = "60"

# Script generation
SCRIPT_VERSION_DEFAULT = "v2_enhanced"
SCRIPT_CACHE_TTL = "3600"

# Frontend is served by the backend Flask application
# No separate frontend service needed