version: 2

services:
  backend:
    source:
      repo: Riishi-01/Passive-Captcha-Model
      branch: main
    build:
      builder: dockerfile
      dockerfile: Dockerfile
    deploy:
      startCommand: python main.py --host 0.0.0.0 --port $PORT --gunicorn
      healthcheckPath: /health
      healthcheckTimeout: 300s
      restartPolicy: onFailure
    environment:
      ENV: production
      FLASK_ENV: production
      PYTHONPATH: /app
      LOG_LEVEL: INFO
      STRUCTURED_LOGGING: "true"
      RATE_LIMIT_ENABLED: "true"
      RATE_LIMIT_PER_MINUTE: "60"
      SCRIPT_VERSION_DEFAULT: v2_enhanced
      SCRIPT_CACHE_TTL: "3600"