[[services]]
name = "passive-captcha-backend"

[services.source]
repo = "Riishi-01/Passive-Captcha-Model"
branch = "main"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile.production"

[services.deploy]
startCommand = "python main.py --host 0.0.0.0 --port $PORT --gunicorn"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Essential Environment Variables
[services.variables]
ENV = "production"
FLASK_ENV = "production"
ADMIN_SECRET = "Admin123"
JWT_SECRET = "jwt-secret-key-for-passive-captcha-production-environment"