# Render Buildpack Configuration
[build]
  [[build.env]]
    name = "NODE_VERSION"
    value = "18.19.0"
  
  [[build.env]]
    name = "NPM_CONFIG_PRODUCTION"
    value = "false"
    
  [[build.env]]
    name = "NODE_ENV"
    value = "production"
    
  [[build.env]]
    name = "CI"
    value = "true"

[deploy]
  [[deploy.env]]
    name = "PYTHON_VERSION" 
    value = "3.11"